// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...

/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApZ6dL0IOReod3UgEJm2t8A7kS76ULMW8',
    appId: '1:808523349516:web:4ea45553b8650c2e18b829',
    messagingSenderId: '808523349516',
    projectId: 'deliveryapp-c1b59',
    authDomain: 'deliveryapp-c1b59.firebaseapp.com',
    storageBucket: 'deliveryapp-c1b59.appspot.com',
    measurementId: 'G-ZCQV8SSXMQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpRH49F01hn6djAqyyP6QKDOhEj-ZHx6o',
    appId: '1:808523349516:android:0dace7073840df7c18b829',
    messagingSenderId: '808523349516',
    projectId: 'deliveryapp-c1b59',
    storageBucket: 'deliveryapp-c1b59.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDzosMu6Uy0_CmkNKRczQGbv84a1aQjNo',
    appId: '1:808523349516:ios:98711a59a216a73818b829',
    messagingSenderId: '808523349516',
    projectId: 'deliveryapp-c1b59',
    storageBucket: 'deliveryapp-c1b59.appspot.com',
    androidClientId:
        '808523349516-psbbe5v0gkn67k374rmglb2475nl3vvq.apps.googleusercontent.com',
    iosClientId:
        '808523349516-b5hcid12b4ji6d2kcf9q216g1ok1nlln.apps.googleusercontent.com',
    iosBundleId: 'com.example.easyGo',
  );
}
